schema_version: 1

context:
  name: bioio
  version: "1.6.1"
  python_min: '3.11'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/bioio-${{ version }}.tar.gz
  sha256: dae300995ee5eeacac6a0d124d6933fd8bb0f005a8e1e541aa1b8bb289fe152c

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=65
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=${{ python_min }}
    - bioio-base ==1.0.7
    - dask-core >=2021.4.1
    - fsspec >=2022.8.0
    - imageio >=2.11.0
    - numpy >=1.21.0
    - ome-types >=0.4.0
    - ome-zarr >=0.6.1
    - ome-zarr-models >=0.1.1
    - scikit-image !=0.23.0
    - semver >=3.0.1
    - tifffile >=2021.8.30
    - zarr >=2.6.0

tests:
  - python:
      imports:
        - bioio_base
      pip_check: false
      python_version: ${{ python_min }}.*

about:
  summary: Image reading, metadata management, and image writing for Microscopy images in Python
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/bioio-devs/bioio

extra:
  recipe-maintainers:
    - imagejan
